# Generated by Django 2.1.2 on 2018-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('reg', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=200)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], max_length=20)),
                ('course', models.CharField(choices=[('btech', 'BTech'), ('mtech', 'MTech')], max_length=20)),
                ('number', models.CharField(max_length=20)),
                ('branch', models.CharField(choices=[('me', 'Mechanical'), ('cse', 'Computer Science'), ('it', 'Information Technology'), ('ece', 'Electronics And Communication'), ('eee', 'Electrical And Electronics')], max_length=20)),
                ('grad', models.CharField(max_length=8)),
                ('org', models.CharField(max_length=250)),
                ('desig', models.CharField(max_length=250)),
                ('domain', models.CharField(choices=[('me', 'Mechanical'), ('cse', 'Computer Science & IT'), ('ece', 'Electronics And Communication'), ('eee', 'Electrical And Electronics'), ('oth', 'Others')], max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('custatus', models.CharField(choices=[('comp', 'Completed'), ('purs', 'Pursuing'), ('noto', 'Not Opted')], max_length=50)),
                ('univname', models.CharField(max_length=100)),
                ('texta', models.TextField()),
                ('textb', models.TextField()),
                ('textc', models.TextField()),
                ('textd', models.TextField()),
                ('texte', models.TextField()),
                ('textf', models.TextField()),
                ('textg', models.TextField()),
            ],
        ),
    ]
