# Generated by Django 2.1.2 on 2018-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='custatus',
            field=models.CharField(choices=[('comp', 'Completed'), ('purs', 'Pursuing'), ('noto', 'Not Opted')], max_length=50, verbose_name='Current Status'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='desig',
            field=models.CharField(max_length=250, verbose_name='Current Designation'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='grad',
            field=models.CharField(max_length=8, verbose_name='Graduation Year'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='org',
            field=models.CharField(max_length=250, verbose_name='Current Organization'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='reg',
            field=models.CharField(max_length=50, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='univname',
            field=models.CharField(max_length=100, verbose_name='University Name'),
        ),
    ]
