# Generated by Django 2.1.2 on 2018-11-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20181110_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='texta',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textb',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textd',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='texte',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textf',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textg',
            field=models.TextField(null=True),
        ),
    ]
