# Generated by Django 2.1.2 on 2018-11-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20181110_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='custatus',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='reg',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='texta',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='textb',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='textc',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='textd',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='texte',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='textf',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='textg',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='univname',
        ),
    ]
