# Generated by Django 2.1.2 on 2018-11-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20181119_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='choicea',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choiceb',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choicec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choiced',
            field=models.BooleanField(default=True),
        ),
    ]
