# Generated by Django 2.1.2 on 2018-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_placement_choicee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='choicea',
            field=models.BooleanField(default=False),
        ),
    ]
