# Generated by Django 2.1.2 on 2018-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_auto_20181119_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='choicea',
            field=models.BooleanField(default=False, verbose_name='Do you think that has helped in building your career?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choiceb',
            field=models.BooleanField(default=False, verbose_name='4.Will you be interested in mentoring some of our students in your domain?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choicec',
            field=models.BooleanField(default=False, verbose_name='\t5.Would you be interested in visiting our campus for a technical talk to our present students?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choiced',
            field=models.BooleanField(default=False, verbose_name='6.Are you aware of any companies in your domain which are looking for freshers?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choicee',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='7.Are you in a position(in your company)to help the recruitments in our campus?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='texta',
            field=models.TextField(null=True, verbose_name='1.What did you do in the year immediately after graduating?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textb',
            field=models.TextField(null=True, verbose_name='2.What are the skills/tools fresher must acquaint with before entering your field?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textc',
            field=models.TextField(null=True, verbose_name='3.What are the topics a fresher must prepare for an interview in your domain?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textd',
            field=models.TextField(null=True, verbose_name='Can you provide the company/HR details?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='texte',
            field=models.TextField(null=True, verbose_name='Will you recomment our institution to the company?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textf',
            field=models.TextField(null=True, verbose_name=' Can you suggest how we can approach your HR?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textg',
            field=models.TextField(null=True, verbose_name='Can you share us your HR contact details?'),
        ),
    ]
