# Generated by Django 2.1.2 on 2018-11-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20181125_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placement',
            name='custatus',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='placement',
            name='univname',
        ),
        migrations.AlterField(
            model_name='placement',
            name='number',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
    ]
