# Generated by Django 2.1.2 on 2019-02-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_remove_placement_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='choicea',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False, verbose_name='Do you think that has helped in building your career?'),
        ),
    ]
