# Generated by Django 2.1.2 on 2019-02-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_auto_20190219_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='choicea',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='Do you think that has helped in building your career?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choiced',
            field=models.BooleanField(default=True, verbose_name='6.Are you aware of any companies in your domain which are looking for freshers?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='choicee',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, verbose_name='7.Are you in a position(in your company)to help the recruitments in our campus?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textd',
            field=models.TextField(blank=True, null=True, verbose_name='Can you provide the company/HR details?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textf',
            field=models.TextField(blank=True, null=True, verbose_name=' Can you suggest how we can approach your HR?'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='textg',
            field=models.TextField(blank=True, null=True, verbose_name='Can you share us your HR contact details?'),
        ),
    ]
