# Generated by Django 2.1.2 on 2019-02-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_auto_20190219_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='reg',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Registration Number'),
        ),
    ]
